### ISSUE TITLE
Make point-and-click output optional

### ISSUE THREAD

**Issue by th-we** [th-we/MEILER#2]
Supply parameter to set `point-and-click` to `#t`, `#f`or to omit it entirely.

**Comment by uliska** [comment]
I actually think this should *generally* be left out because choosing `point-and-click` should be the responsibility of the person or tool triggering the actual LilyPond rendering. I see no use hard-coding this into the file.

The current behaviour probably results from Klaus's original use case, but even there that switch should be promoted to the next stage in the toolchain.

**Comment by rettinghaus** [comment]
@uliska is right, this should be handled after conversion. (Fixed this in upstream.)
